name: CI
on: [workflow_dispatch, push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/develop.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install wheel
          python3 -m pip install -r ./develop.txt
          python3 -m pip install .

      - name: Run Ruff
        uses: chartboost/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Upgrade pip
        run: python3 -m pip install --upgrade pip

      - name: Get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('**/develop.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python3 -m pip install wheel pytest
          python3 -m pip install -r ./develop.txt
          python3 -m pip install .

      - name: Run Pytest
        run: pytest

  upload_test_pypi:
      name: Upload test PyPI servers
      runs-on: ubuntu-latest
      needs: [lint, test]
      if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/master')
      permissions:
        id-token: write

      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.8'  

        - name: Upgrade pip
          run: python3 -m pip install --upgrade pip

        - name: Get pip cache dir
          id: pip-cache
          run: echo "::set-output name=dir::$(pip cache dir)"

        - name: Cache dependencies
          uses: actions/cache@v4
          with:
            path: ${{ steps.pip-cache.outputs.dir }}
            key: ${{ runner.os }}-pip-${{ hashFiles('**/develop.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-

        - name: Install dependencies
          run: |
            python3 -m pip install wheel
            python3 -m pip install -r ./develop.txt
            python3 -m pip install .
            pip install build
            
        - name: Build package
          run: python -m build

        - name: Upload PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            repository_url: https://test.pypi.org/legacy/
            skip_existing: true
            verbose: true