name: CI
on: [workflow_dispatch, push, pull_request]

env:
  PYPIBUILD: 1
  PYPITEST: 1

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: '**/develop.txt'

      - name: Install dependencies
        run: |
          python3 -m pip install wheel
          python3 -m pip install -r ./develop.txt
          python3 -m pip install .

      - name: Run Ruff
        uses: chartboost/ruff-action@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: '**/develop.txt'

      - name: Install dependencies
        run: |
          python3 -m pip install wheel pytest
          python3 -m pip install -r ./develop.txt
          python3 -m pip install .

      - name: Run Pytest
        run: pytest

  upload_test_pypi:
    name: Upload test PyPI servers
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/heads/master')
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: '**/develop.txt'

      - name: Install dependencies
        run: |
          python3 -m pip install wheel
          python3 -m pip install -r ./develop.txt
          python3 -m pip install .
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true
          verbose: true

  install_test_pypi:
    name: Install test wheel ${{ matrix.os }} - ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    needs: [upload_test_pypi]
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: '**/develop.txt'

      - name: Install package
        run: |
          python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple pgpd

      - name: Run package
        run: |
          python -c "import pgpd; print(f'PGPD Version {pgpd.__version__}')"