name: Release

on:
  release:
    types: [published]

env:
  PYPIBUILD: 1

jobs:
  upload_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: '**/develop.txt'

      - name: Install dependencies
        run: |
          python3 -m pip install wheel
          python3 -m pip install -r ./develop.txt
          python3 -m pip install .
          pip install build

      - name: Build package
        run: python -m build
        
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}

  pages:
    runs-on: ubuntu-18.04
    needs: upload_pypi
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: '**/develop.txt'

      - name: Install dependencies
        run: |
          python3 -m pip install wheel
          python3 -m pip install -r ./develop.txt
          python3 -m pip install .

      - name: Build documentation
        run: |
          cd docs
          make clean html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html

  install_test_pypi:
    name: Install wheel ${{ matrix.os }} - ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    needs: upload_pypi
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
          cache: pip
          cache-dependency-path: '**/develop.txt'

      - name: Install package
        run: |
          python -m pip install pgpd

      - name: Run package
        run: |
          python -c "import pgpd; print(f'PGPD Version {pgpd.__version__}')"
